name: auto_assign_tasks
description: >
  Automatically match pending unblocked tasks to idle agents.
  Runs on a schedule, queries for pending unblocked tasks and idle agents,
  and assigns the highest-priority task to the first available agent.
enabled: true

triggers:
  - type: scheduled
    with:
      every: 30s

steps:
  - name: find_pending_tasks
    type: elasticsearch.request
    with:
      method: POST
      path: /codefleet-tasks/_search
      body:
        size: 10
        query:
          bool:
            must:
              - term:
                  status: pending
            must_not:
              - wildcard:
                  blocked_by: "*"
        sort:
          - priority:
              order: desc
          - created_at:
              order: asc

  - name: find_idle_agents
    type: elasticsearch.search
    with:
      index: codefleet-agents
      size: 10
      query:
        term:
          status: idle

  - name: check_and_assign
    type: if
    condition: "steps.find_pending_tasks.output.hits.total.value > 0 and steps.find_idle_agents.output.hits.total.value > 0"
    steps:
      - name: assign_task
        type: elasticsearch.update
        with:
          index: codefleet-tasks
          id: "{{ steps.find_pending_tasks.output.hits.hits[0]._id }}"
          doc:
            status: assigned
            assigned_to: "{{ steps.find_idle_agents.output.hits.hits[0]._id }}"
            assigned_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
            updated_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

      - name: update_agent
        type: elasticsearch.update
        with:
          index: codefleet-agents
          id: "{{ steps.find_idle_agents.output.hits.hits[0]._id }}"
          doc:
            status: working
            current_task_id: "{{ steps.find_pending_tasks.output.hits.hits[0]._id }}"
            updated_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

      - name: log_assignment
        type: elasticsearch.index
        with:
          index: codefleet-activity
          document:
            event_type: task_assigned
            agent_id: "{{ steps.find_idle_agents.output.hits.hits[0]._id }}"
            task_id: "{{ steps.find_pending_tasks.output.hits.hits[0]._id }}"
            message: "Auto-assigned task to idle agent"
            timestamp: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
    else:
      - name: log_no_match
        type: console
        with:
          message: "No pending tasks or idle agents to match"
