name: handle_task_completion
description: >
  Fires when a task completes. Finds all tasks whose depends_on list
  contains the completed task_id, removes it from their blocked_by lists,
  and moves fully-unblocked tasks to pending status.
enabled: true

triggers:
  - type: manual
  - type: alert

inputs:
  - name: completed_task_id
    type: string
    required: true
    description: "The task_id of the completed task"

steps:
  - name: find_dependent_tasks
    type: elasticsearch.search
    with:
      index: codefleet-tasks
      size: 50
      query:
        bool:
          must:
            - match:
                blocked_by: "{{ inputs.completed_task_id }}"

  - name: unblock_if_found
    type: if
    condition: "steps.find_dependent_tasks.output.hits.total.value > 0"
    steps:
      - name: process_each_dependent
        type: foreach
        foreach: steps.find_dependent_tasks.output.hits.hits
        steps:
          - name: unblock_task
            type: elasticsearch.request
            with:
              method: POST
              path: "/codefleet-tasks/_update/{{ foreach.item._id }}"
              body:
                script:
                  source: >
                    if (ctx._source.blocked_by instanceof List) {
                      ctx._source.blocked_by.removeIf(id -> id == params.completed_id);
                      if (ctx._source.blocked_by.size() == 0) {
                        ctx._source.status = 'pending';
                      }
                    } else if (ctx._source.blocked_by instanceof String && ctx._source.blocked_by.contains(params.completed_id)) {
                      ctx._source.blocked_by = '';
                      ctx._source.status = 'pending';
                    }
                    ctx._source.updated_at = params.now;
                  params:
                    completed_id: "{{ inputs.completed_task_id }}"
                    now: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

      - name: log_unblock_event
        type: elasticsearch.index
        with:
          index: codefleet-activity
          document:
            event_type: task_unblocked
            task_id: "{{ inputs.completed_task_id }}"
            message: "Task completed — unblocked {{ steps.find_dependent_tasks.output.hits.total.value }} dependent tasks"
            timestamp: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
    else:
      - name: log_no_dependents
        type: console
        with:
          message: "No dependent tasks found for {{ inputs.completed_task_id }}"
